#!/bin/bash
set -e

# This file was entirely AI generated by Google Gemini 3 Pro
# I am NOT handwriting a installation shell script

# Configuration
WRAPPER_DIR=$(pwd)
BUILD_BIN_DIR="$WRAPPER_DIR/build_linux/bin"
APP_NAME="Goo Engine"
APP_BINARY_NAME="goo-engine"
ICON_NAME="goo-engine"

# Installation Destinations (User Local)
INSTALL_DIR="$HOME/.local/share/goo-engine"
BIN_LINK_DIR="$HOME/.local/bin"
DESKTOP_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons/hicolor/scalable/apps"

echo "=== Installing $APP_NAME ==="

# 1. Verify Build Exists
if [ ! -f "$BUILD_BIN_DIR/blender" ]; then
    echo "Error: Compiled binary not found at $BUILD_BIN_DIR/blender"
    echo "Please run build_goo_engine.sh first to compile the project."
    exit 1
fi

# 2. Create Directories
echo "Creating installation directories..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$BIN_LINK_DIR"
mkdir -p "$DESKTOP_DIR"
mkdir -p "$ICON_DIR"

# 3. Copy Files
echo "Copying application files to $INSTALL_DIR..."
# Remove old install if it exists to ensure clean state
if [ -d "$INSTALL_DIR" ]; then
    rm -rf "$INSTALL_DIR"
fi
# Copy the 'bin' folder contents to the install dir
cp -r "$BUILD_BIN_DIR" "$INSTALL_DIR"

# 4. Install Icon
echo "Installing Icon..."
# Check for blender.svg, create a copy named goo-engine.svg in the system icon path
if [ -f "$INSTALL_DIR/blender.svg" ]; then
    cp "$INSTALL_DIR/blender.svg" "$ICON_DIR/$ICON_NAME.svg"
    echo "Icon installed to $ICON_DIR/$ICON_NAME.svg"
else
    echo "Warning: blender.svg not found. Skipping icon install."
fi

# 5. Configure & Install Desktop File
echo "Configuring Desktop Entry..."
SOURCE_DESKTOP="$INSTALL_DIR/blender.desktop"
TARGET_DESKTOP="$DESKTOP_DIR/$APP_BINARY_NAME.desktop"

if [ -f "$SOURCE_DESKTOP" ]; then
    # Read the original desktop file and modify it on the fly
    # 1. Change Name=Blender to Name=Goo Engine
    # 2. Change Exec=blender to absolute path
    # 3. Change Icon=blender to our custom icon name
    
    sed \
        -e "s|^Name=.*|Name=$APP_NAME|" \
        -e "s|^Exec=.*|Exec=$INSTALL_DIR/blender %f|" \
        -e "s|^Icon=.*|Icon=$ICON_NAME|" \
        "$SOURCE_DESKTOP" > "$TARGET_DESKTOP"

    chmod +x "$TARGET_DESKTOP"
    echo "Desktop file created at $TARGET_DESKTOP"
else
    echo "Warning: blender.desktop not found in build output. Menu entry skipped."
fi

# 6. Create Command Line Symlink
echo "Creating terminal command..."
# Links ~/.local/bin/goo-engine -> ~/.local/share/goo-engine/blender
ln -sf "$INSTALL_DIR/blender" "$BIN_LINK_DIR/$APP_BINARY_NAME"

# 7. Update Databases (if tools exist)
if command -v update-desktop-database &> /dev/null; then
    update-desktop-database "$DESKTOP_DIR" || true
fi
if command -v gtk-update-icon-cache &> /dev/null; then
    # Attempt to update icon cache, might fail on user dirs without specific flags, so we allow failure
    gtk-update-icon-cache "$HOME/.local/share/icons/hicolor" &> /dev/null || true
fi

echo "=== Installation Complete ==="
echo "1. Launch from App Menu: Search for '$APP_NAME'"
echo "2. Launch from Terminal: Type '$APP_BINARY_NAME'"
echo ""
echo "Note: If '$APP_BINARY_NAME' is not found in terminal, ensure '$HOME/.local/bin' is in your \$PATH."
